### ISSUE TITLE
Streamers do not get general rewards when enabled

### ISSUE THREAD

**Issue by cybermancerr** [morelaid/StreamDrops#2]
Streamers not getting general rewards when set to true in settings file.  Version 9.3 of the plug-in.  Viewers get all general drops.  Note:  drop rate is at 100% every 15 minutes.  Server is on paper 1.18.2

**Comment by morelaid** [comment]
> Streamers not getting general rewards when set to true in settings file.  Version 9.3 of the plug-in.  Viewers get all general drops.  Note:  drop rate is at 100% every 15 minutes.  Server is on paper 1.18.2

Please use one of my offered support options. Other ways complicate with the processing, because they can be overlooked unintentionally.

The support ways are visible on the "SpigotMC" page or also here in the wiki.

Now to your problem:
Your statement "Setting the option" in the settings to "true" is unfortunately too general. Which option (name) do you mean?
Regardless, there is no such setting. StreamingDrops is designed for viewers, so a streamer cannot collect drops himself. Only if the streamer is a viewer of another streamer, the viewer can receive drops. So I don't see this as a bug, but as a wrong understanding of a setting option.
Streamers get more / new viewers, through the possibilities of StreamingDrops - the interest in a streamer is increased. Thus, the main reward for a streamer is the viewers.

Here you can find an overview of the support channels I offer and the support channels I want to offer:

https://github.com/morelaid/StreamDrops/wiki#support


By the way, here are some option values explained, maybe this will help you. If not or if you would like to have more background knowledge / another explanation to a setup point, feel free to contact me.

https://github.com/morelaid/StreamDrops/wiki/Setup#overview-of-the-settings

**Comment by cybermancerr** [comment]
Ah that makes sense.  Thank you for the explanation.
