### ISSUE TITLE
Ability to modify Twitch Emoji formats 

### ISSUE THREAD

**Issue by Gabo6480** [morelaid/StreamDrops#3]
On my server I'm using the plugin ItemsAdder to allow using emojis in the Minecraft's chat. Although it requires the name of the emoji to be in between : :.
Example:   :happy: 
However when mirroring the twitch chat into Minecraft all emojis are sent to the chat without any formatting. I'd like to have a way to override this in order to allow the mirrored twitch chat to use the emojis that I've set up with ItemsAdder

**Comment by morelaid** [comment]
To begin, I would be happy if we make requests, through the channels I offer. The reason for this is that processing via GitHub and the way I have currently set it up means significantly more work. In addition, it can happen that I unintentionally overlook requests here, because this is not part of my workflow.

So I would be happy if you use one of my offered ways. Discord is the fastest possible way to get a feedback (notification system). This makes the work / processing of requests on my side easier :)

To your request:
Whether this is possible, I can not say exactly. I would have to see if I can recognize emojis to be able to change the format on this. Thus I can not promise this, whether there can be a function update for this. But I will check this later

![Support Section](https://user-images.githubusercontent.com/37469978/179459740-bf80f675-bcbd-4ce3-8a11-d3b31143801b.jpeg)

**Comment by morelaid** [comment]
This is currently not possible for various (among other technical) reasons. I would close this topic for now. It may be that this will change in the future, but currently this feature will not (be able to) exist.

**Comment by Gabo6480** [comment]
How about having a config setting that allows you to replace certain strings form the chat's messages with other certain strings? So, for example, the server admin declares to replace the "heart" string with "♥", or to replace the string "LUL" with ":lul:" (Which could be an ItemsAdder emoji). This would limit it's scope to only what the admin declares, however it could also work as profanity filter.

**Comment by morelaid** [comment]
As already mentioned, this cannot be implemented reasonably at the moment for various reasons. It is not and never was the goal to get a 100% representation of the Twitch chat in Minecraft. At the end of the day, this is not possible because one is text-based and the other is a website. In addition, plugins / add ons can and do make enhancements to the Twitch chat pages that are considered standard by some. But these can not be transferred to Minecraft.

I said not without reason that this currently does not work well / cleanly for several reasons. I can list a few things from this, but would appreciate you respecting when I say it doesn't work as directly. You have your perspective, but I have one about hundreds of other streamers who also use the plugin.

- I don't want to have a dependency on a paid plugin as a developer. Especially when my plugin could actually be paid (this would be fair)
- Not all emotes can be supported. Not even all that are in the own Twitch chat
- Through plugins / add ons in Twitch Chat there are now again felt thousands of other emotes (BetterTwitchTV, 7TV, FrankerFraceZ and many more)
- My goal is not to enable a one-to-one mapping of the chat, but to enable the streamer a small tool, with which you do not have to look at another monitor in phases in which you have to concentrate.
- Technically I only get one text. If I replace things, chaos results. Example: "What is your heartbeat right now?" | "My heart vomits when I look at this" | "You have to click on the heart". These are sentences without emotes, but here it could happen very quickly that an emote is replaced. The positive / false rate is just too high for me for emotes that are used in a sentence, but are not emotes at all.
- Emotes cannot be displayed directly in Minecraft chat. I can't give support for an external plugin that I don't know myself (and don't want to in the end), but this will happen. How I know this.... Because it has already happened. On a small scale "can you help me here and there too, your support is at least fast, understandable and helpful". These are nice compliments, but I do this in the end only as a hobby / out of boredom and do not earn my living with it

I don't know if you were or are aware before that I didn't just "let the time pass", but I was dealing with the issue. Perhaps this has now come across a little better. "Yes, I took your request seriously. Yes, I have dealt with it. And yes, I have also thought this through". Even though the result may not be quite what you hoped for, not all of your requests were denied. Others have been implemented and can already be actively used.

I hope my views and also reasons are a bit clearer now.
This has now become a wall of text, but perhaps it will help you in the end to understand whether I was careless in my previous answer or not.

**Comment by Gabo6480** [comment]
I respect your perspective as the developer of the plugin. I know you might have your reasons, however, I do feel you are being a little unreasonable. As such, allow me to refute some of your points.

- You wouldn't have to have a dependency on anything at all. This feature would be an interaction between systems. ItemsAdder is just one example of a method to add custom emojis/characters to the minecraft's chat. As such, there are many other methods to achieve this. For example, creating a resource pack that replaces Chinese characters with other custom characters on the client's side. I believe that, if a server developer has already gone through the task of implementing support of some emojis in their Minecraft chat, they might as well desire to have them work with your plugin's refection of Twitch's chat.
- It is your own prerogative whether or not you charge for your plugin. I personally would have paid for it regardless if you did. 
- I understand that having full support to the WHOLE variety of Twitch's (and its Addons) emotes might be unreasonable or outright impossible. That's why I feel that my previous suggestion is a decent compromise for a reasonable feature.
- Even though there might be thousands of emotes, in every chat there are generally some that are drastically used more than others. As such, with this feature, a server developer will have the option to implement support for only those.
- I comprehend your worry about false positives. However, the intention of the "heart to ♥" example was just to illustrate on how the feature would work. On practice, on the other hand, all of the Twitch(+ Addons)'s emotes have very specific, recognizable, and unique strings representing them. So the chance of a false positive is close to null. AND, for your information, Twitch(+ Addons) way of showing emotes work in the exact same way, by detecting specific strings an replacing them with something else (in their case, an image).
- It is your own prerogative what you do as a hobby and how you manage it. Part of developing any piece of software is receiving suggestions. I myself have been dabbling on plugin development recently as a hobby too, however, I prefer to contribute to already existing, open source, plugins. I would implement (and publish) this feature myself if your plugin was open source as well, however, I do respect your decision to keep it private and I won't push you on that regard.

**Comment by morelaid** [comment]
If you program yourself, I can't understand why you don't include this without my source code. It will be easy from your side to replace the texts. They are messages sent to the player and you can change them. Any plugin can query messages sent to a player and do anything with the message.

That to a programming belong also inquiries, may be. Nobody is forced to implement everything. This is up to the developer and a justification is not even necessary (even if I have given an extensive, albeit incomplete explanation).

Regardless of the topic, you should know that I check requests and also implement them very often. This happened again today alone and also with one of your requests.
The Twitch emotes integration will not be available from my side for now, but you seem to be able to build this yourself, so you are welcome to build an extra plugin which modifies the messages.
The source code is not open source for various reasons and it will stay that way for now. But for an external plugin you don't need one line of my (StreamingDrops) code.

I consider this ticket closed. Even if there was no direct implementation for you in this case / the request was rejected by me, I consider the questions answered.
