### ISSUE TITLE
Twich chat mirror: Access to more user parameters

### ISSUE THREAD

**Issue by Gabo6480** [morelaid/StreamDrops#4]
In the twitch chat mirror I would like to be able to access to the following values:

A chatter's username color though placeholders.
A chatter's badges through placeholders, and being able to configure the tag for each of the possible badges.

**Comment by morelaid** [comment]
Here is just the little reminder about my support ways to make my job easier.

About your request:
I would split your request into two parts. I can understand the different colors for the Twitch viewers in the chat. I have also thought about this before and this would also be conceivable. I can not promise anything at this point.

The second part with the badges is another issue. On the one hand, there is the problem that there are a lot of badges and new ones are added all the time.
If these are then in, the next request comes "Yes, what about the BetterTwitchTV" stuff. At the end of the day, the adoption of the Twitch chat into the Minecraft client is not to offer the full features of the Twitch chat with all its extensibility. It's mainly about the messaging, so that in situations where you need to be focused, you don't have to move your head too much to chat.
Thus, I may not include that part, because the goal of StreamingDrops is not to rebuild Twitch Chat. This is really just a very minor feature. Moreover, it can lead to many individual problems and does not make configuration any easier.

![image](https://user-images.githubusercontent.com/37469978/179462239-e0db6e55-afd0-466d-a4e5-ddff08461f9a.jpeg)

**Comment by morelaid** [comment]
User color of Twitch user was added in version 10.3.
Badges are not supported at the moment

https://www.spigotmc.org/resources/streamingdrops-1-8-8-1-19-x-twitch-drops-for-minecraft-server-twitch-integration.76996/update?update=466810
